### PR TITLE
update Kubernetes to 1.31.0-rc.0

### PR DESCRIPTION
**Pull request by dfajmon**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Bump Kubernetes to v1.31.0-rc.0

**Special notes for your reviewer**:
1. Updated calling of `featuregatetesting.SetFeatureGateDuringTest`
2. `v1.PersistentVolumeClaimControllerResizeFailed -> v1.PersistentVolumeClaimControllerResizeInfeasible` 

**Does this PR introduce a user-facing change?**:

```release-note
Updates Kubernetes dependencies to 1.31.0-rc.0
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm cancel
this needs bigger changes to accommodate the API changes, likely in https://github.com/kubernetes-csi/external-resizer/pull/418

**Comment by solumath** [comment]
https://github.com/kubernetes-csi/external-resizer/pull/418 - Expected to bump kubernetes with more changes
/close

**Comment by dfajmon** [comment]
https://github.com/kubernetes-csi/external-resizer/pull/418 - Expected to bump kubernetes with more changes

**Pull request closed without merging**
