### PR TITLE
feat: Add migrated label to metrics

### PR DESCRIPTION
**Pull request by nearora-msft**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:
This PR is an extension to kubernetes-csi/csi-lib-utils#77 to send "migrated" label in the metrics

**Which issue(s) this PR fixes**:
Partially Addressed # kubernetes/kubernetes#98279

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Set the value of "migrated" field in the metrics to true or false to indicate if the call is a migration enabled feature or not
```

### CODE REVIEW

**Comment by nearora-msft** [comment]
@Jiawei0227 Could you please look at this draft PR to see if things looks ok?

**Comment by Jiawei0227** [comment]
/lgtm

I tested this in my dev environment and it is working. One thing to call out is https://github.com/kubernetes-csi/external-resizer/issues/137 this need to be done otherwise the resize will not work. We need to do before the next resizer release

**Comment by Jiawei0227** [comment]
@msau42 for final approval.

**Comment by msau42** [comment]
/approve

@Jiawei0227 are you able to update csi-translation-lib now? We can use a specific hash I think

**Pull request merged**
