### PR TITLE
Add prometheus metrics to CSI external-resizer using new csi-lib-utils library

### LINKED ISSUE #37: Capture metrics for external volume resizing

### PR DESCRIPTION
**Pull request by saad-ali**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR adds metrics to the external-resizer CSI gRPC calls:

* `csi_sidecar_operations_seconds` [ALPHA] Container Storage Interface operation duration with gRPC error code status total

**Which issue(s) this PR fixes**:

Fixes #37 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add prometheus metrics to CSI external-resizer under the /metrics endpoint. This can be enabled via the "--metrics-address" and "--metrics-path" options.
```

### CODE REVIEW

**Comment by saad-ali** [comment]
Looks like `external-resizer` is still on old go version: 

https://github.com/kubernetes-csi/external-resizer/blob/b17c84a38e5335cf8dfd0576c6d3230376a4ed3e/release-tools/travis.yml#L9

@pohly can you help update release tools for this repo?

**Comment by saad-ali** [comment]
Opened https://github.com/kubernetes-csi/external-resizer/pull/68 to update release-tools

**Comment by verult** [comment]
@mattcary @saikat-royc

**Pull request merged**
