### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by humblec**
This PR correct the markdown linter errors on the resizer sidecar readme.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by gnufied** [comment]
Can you update the PR description about what we are changing?

**Comment by humblec** [comment]
> Can you update the PR description about what we are changing?

@gnufied done. please check, thanks :+1:

**Comment by humblec** [comment]
@gnufied or @msau42 can you please approve this too ?

**Pull request merged**
