### PR TITLE
release-1.2: update release-tools

### PR DESCRIPTION
**Pull request by pohly**
Squashed 'release-tools/' changes from bc0504a..a6a1a79

[a6a1a79](https://github.com/kubernetes-csi/csi-release-tools/commit/a6a1a79) Merge [pull request #176](https://github.com/kubernetes-csi/csi-release-tools/pull/176) from pohly/go-1.17.3
[0a2cf63](https://github.com/kubernetes-csi/csi-release-tools/commit/0a2cf63) prow.sh: bump Go to 1.17.3
[fc29fdd](https://github.com/kubernetes-csi/csi-release-tools/commit/fc29fdd) Merge [pull request #141](https://github.com/kubernetes-csi/csi-release-tools/pull/141) from pohly/prune-replace-optional
[5b9a1e0](https://github.com/kubernetes-csi/csi-release-tools/commit/5b9a1e0) Merge [pull request #175](https://github.com/kubernetes-csi/csi-release-tools/pull/175) from jimdaga/patch-1
[5eeb602](https://github.com/kubernetes-csi/csi-release-tools/commit/5eeb602) images: use k8s-staging-test-infra/gcb-docker-gcloud
[5489de6](https://github.com/kubernetes-csi/csi-release-tools/commit/5489de6) Merge [pull request #174](https://github.com/kubernetes-csi/csi-release-tools/pull/174) from mauriciopoppe/bump-kind-version
[0c675d4](https://github.com/kubernetes-csi/csi-release-tools/commit/0c675d4) Bump kind version to v0.11.1
[ef69a88](https://github.com/kubernetes-csi/csi-release-tools/commit/ef69a88) Merge [pull request #173](https://github.com/kubernetes-csi/csi-release-tools/pull/173) from nick5616/add-ws2022
[44c710c](https://github.com/kubernetes-csi/csi-release-tools/commit/44c710c) added WS2022 to build platforms
[0883be4](https://github.com/kubernetes-csi/csi-release-tools/commit/0883be4) Merge [pull request #171](https://github.com/kubernetes-csi/csi-release-tools/pull/171) from pohly/example-commands
[02cda51](https://github.com/kubernetes-csi/csi-release-tools/commit/02cda51) build.make: support binaries outside of cmd, with optional go.mod
[65922ea](https://github.com/kubernetes-csi/csi-release-tools/commit/65922ea) Merge [pull request #170](https://github.com/kubernetes-csi/csi-release-tools/pull/170) from pohly/canary-snapshot-controller
[c0bdfb3](https://github.com/kubernetes-csi/csi-release-tools/commit/c0bdfb3) prow.sh: deploy canary snapshot-controller in canary jobs
[0438f15](https://github.com/kubernetes-csi/csi-release-tools/commit/0438f15) Merge [pull request #167](https://github.com/kubernetes-csi/csi-release-tools/pull/167) from c0va23/feature/release-armv7-image
[4786f4d](https://github.com/kubernetes-csi/csi-release-tools/commit/4786f4d) Merge [pull request #168](https://github.com/kubernetes-csi/csi-release-tools/pull/168) from msau42/update-release-prereq
[6a2dc64](https://github.com/kubernetes-csi/csi-release-tools/commit/6a2dc64) Remove requirement to be top-level approver. Only maintainers membership is required to do a release
[30a4f7b](https://github.com/kubernetes-csi/csi-release-tools/commit/30a4f7b) Release armv7 image
[ac8108f](https://github.com/kubernetes-csi/csi-release-tools/commit/ac8108f) Merge [pull request #165](https://github.com/kubernetes-csi/csi-release-tools/pull/165) from consideRatio/pr/update-github-links-ref-to-master-to-HEAD
[999b483](https://github.com/kubernetes-csi/csi-release-tools/commit/999b483) docs: make github links reference HEAD instead of main
[fd67069](https://github.com/kubernetes-csi/csi-release-tools/commit/fd67069) docs: make github links reference HEAD instead of master
[c0a4fb1](https://github.com/kubernetes-csi/csi-release-tools/commit/c0a4fb1) Merge [pull request #164](https://github.com/kubernetes-csi/csi-release-tools/pull/164) from anubha-v-ardhan/patch-1
[9c6a6c0](https://github.com/kubernetes-csi/csi-release-tools/commit/9c6a6c0) Master to main cleanup
[682c686](https://github.com/kubernetes-csi/csi-release-tools/commit/682c686) Merge [pull request #162](https://github.com/kubernetes-csi/csi-release-tools/pull/162) from pohly/pod-name-via-shell-command
[36a29f5](https://github.com/kubernetes-csi/csi-release-tools/commit/36a29f5) Merge [pull request #163](https://github.com/kubernetes-csi/csi-release-tools/pull/163) from pohly/remove-bazel
[68e43ca](https://github.com/kubernetes-csi/csi-release-tools/commit/68e43ca) prow.sh: remove Bazel build support
[c5f59c5](https://github.com/kubernetes-csi/csi-release-tools/commit/c5f59c5) prow.sh: allow shell commands in CSI_PROW_SANITY_POD
[71c810a](https://github.com/kubernetes-csi/csi-release-tools/commit/71c810a) Merge [pull request #161](https://github.com/kubernetes-csi/csi-release-tools/pull/161) from pohly/mock-test-fixes
[9e438f8](https://github.com/kubernetes-csi/csi-release-tools/commit/9e438f8) prow.sh: fix mock testing
[d7146c7](https://github.com/kubernetes-csi/csi-release-tools/commit/d7146c7) Merge [pull request #160](https://github.com/kubernetes-csi/csi-release-tools/pull/160) from pohly/kind-update
[4b6aa60](https://github.com/kubernetes-csi/csi-release-tools/commit/4b6aa60) prow.sh: update to KinD v0.11.0
[7cdc76f](https://github.com/kubernetes-csi/csi-release-tools/commit/7cdc76f) Merge [pull request #159](https://github.com/kubernetes-csi/csi-release-tools/pull/159) from pohly/fix-deployment-selection
[ef8bd33](https://github.com/kubernetes-csi/csi-release-tools/commit/ef8bd33) prow.sh: more flexible CSI_PROW_DEPLOYMENT, part II
[204bc89](https://github.com/kubernetes-csi/csi-release-tools/commit/204bc89) Merge [pull request #158](https://github.com/kubernetes-csi/csi-release-tools/pull/158) from pohly/fix-deployment-selection
[61538bb](https://github.com/kubernetes-csi/csi-release-tools/commit/61538bb) prow.sh: more flexible CSI_PROW_DEPLOYMENT
[2b0e6db](https://github.com/kubernetes-csi/csi-release-tools/commit/2b0e6db) Merge [pull request #157](https://github.com/kubernetes-csi/csi-release-tools/pull/157) from humblec/csi-release
[a2fcd6d](https://github.com/kubernetes-csi/csi-release-tools/commit/a2fcd6d) Adding myself to csi reviewers group
[f325590](https://github.com/kubernetes-csi/csi-release-tools/commit/f325590) Merge [pull request #149](https://github.com/kubernetes-csi/csi-release-tools/pull/149) from pohly/cluster-logs
[4b03b30](https://github.com/kubernetes-csi/csi-release-tools/commit/4b03b30) Merge [pull request #155](https://github.com/kubernetes-csi/csi-release-tools/pull/155) from pohly/owners
[a6453c8](https://github.com/kubernetes-csi/csi-release-tools/commit/a6453c8) owners: introduce aliases
[ad83def](https://github.com/kubernetes-csi/csi-release-tools/commit/ad83def) Merge [pull request #153](https://github.com/kubernetes-csi/csi-release-tools/pull/153) from pohly/fix-image-builds
[5561780](https://github.com/kubernetes-csi/csi-release-tools/commit/5561780) build.make: fix image publishng
[29bd39b](https://github.com/kubernetes-csi/csi-release-tools/commit/29bd39b) Merge [pull request #152](https://github.com/kubernetes-csi/csi-release-tools/pull/152) from pohly/bump-csi-test
[bc42793](https://github.com/kubernetes-csi/csi-release-tools/commit/bc42793) prow.sh: use csi-test v4.2.0
[b546baa](https://github.com/kubernetes-csi/csi-release-tools/commit/b546baa) Merge [pull request #150](https://github.com/kubernetes-csi/csi-release-tools/pull/150) from mauriciopoppe/windows-multiarch-args
[bfbb6f3](https://github.com/kubernetes-csi/csi-release-tools/commit/bfbb6f3) add parameter base_image and addon_image to BUILD_PARAMETERS
[2d61d3b](https://github.com/kubernetes-csi/csi-release-tools/commit/2d61d3b) Merge [pull request #151](https://github.com/kubernetes-csi/csi-release-tools/pull/151) from humblec/cm
[48e71f0](https://github.com/kubernetes-csi/csi-release-tools/commit/48e71f0) Replace `which` command ( non standard)  with `command -v` builtin
[feb20e2](https://github.com/kubernetes-csi/csi-release-tools/commit/feb20e2) prow.sh: collect cluster logs
[7b96bea](https://github.com/kubernetes-csi/csi-release-tools/commit/7b96bea) Merge [pull request #148](https://github.com/kubernetes-csi/csi-release-tools/pull/148) from dobsonj/add-checkpathcmd-to-prow
[2d2e03b](https://github.com/kubernetes-csi/csi-release-tools/commit/2d2e03b) prow.sh: enable -csi.checkpathcmd option in csi-sanity
[09d4151](https://github.com/kubernetes-csi/csi-release-tools/commit/09d4151) Merge [pull request #147](https://github.com/kubernetes-csi/csi-release-tools/pull/147) from pohly/mock-testing
[74cfbc9](https://github.com/kubernetes-csi/csi-release-tools/commit/74cfbc9) prow.sh: support mock tests
[4a3f110](https://github.com/kubernetes-csi/csi-release-tools/commit/4a3f110) prow.sh: remove obsolete test suppression
[6616a6b](https://github.com/kubernetes-csi/csi-release-tools/commit/6616a6b) Merge [pull request #146](https://github.com/kubernetes-csi/csi-release-tools/pull/146) from pohly/kubernetes-1.21
[510fb0f](https://github.com/kubernetes-csi/csi-release-tools/commit/510fb0f) prow.sh: support Kubernetes 1.21
[c63c61b](https://github.com/kubernetes-csi/csi-release-tools/commit/c63c61b) prow.sh: add CSI_PROW_DEPLOYMENT_SUFFIX
[51ac11c](https://github.com/kubernetes-csi/csi-release-tools/commit/51ac11c) Merge [pull request #144](https://github.com/kubernetes-csi/csi-release-tools/pull/144) from pohly/pull-jobs
[dd54c92](https://github.com/kubernetes-csi/csi-release-tools/commit/dd54c92) pull-test.sh: test importing csi-release-tools into other repo
[7d2643a](https://github.com/kubernetes-csi/csi-release-tools/commit/7d2643a) Merge [pull request #143](https://github.com/kubernetes-csi/csi-release-tools/pull/143) from pohly/path-setup
[6880b0c](https://github.com/kubernetes-csi/csi-release-tools/commit/6880b0c) prow.sh: avoid creating paths unless really running tests
[b46691a](https://github.com/kubernetes-csi/csi-release-tools/commit/b46691a) go-get-kubernetes.sh: make replace statement pruning optional

git-subtree-dir: release-tools
git-subtree-split: a6a1a7979bf3ebc2bb10d0e33dd11ab281d6d39e

```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
This has problems with owner files.

**Comment by pohly** [comment]
> This has problems with owner files.

Fixed. The aliases symlink was missing.

**Comment by xing-yang** [comment]
/assign @gnufied 

for approval

**Comment by pohly** [comment]
/assign @msau42 

For approval.

**Pull request merged**
