### PR TITLE
Omit extranous dash with CSI timeout parameter

### PR DESCRIPTION
**Pull request by timoreimann**
**What type of PR is this?**
/kind documentation

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig-storage

### CODE REVIEW

**Comment by timoreimann** [comment]
CI failure is:

```
fail("Go toolchain does not support c...")
```

So probably not due to my change, yet wondering if a flake that persist retrying would overcome eventually. 🤔

**Comment by msau42** [comment]
Our CI Is broken: #66 

I will force merge for now because this is purely a readme change and doesn't impact the tests

**Pull request merged**
